# Generated by Django 6.0.8 on 2026-09-02 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCycle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('week_start', models.DateField()),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[('COLLECTING', 'Collecting'), ('CLOSED', 'Closed')],
                        default='COLLECTING',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'facilitator',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='facilitated_cycles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cycles',
                        to='projects.project',
                    ),
                ),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='CycleParticipation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('card_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cycle_participations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'cycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participations',
                        to='cycles.feedbackcycle',
                    ),
                ),
            ],
            options={
                'unique_together': {('cycle', 'user')},
            },
        ),
    ]
