# Generated by Django 6.0.8 on 2026-09-02 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('DRAFT', 'Draft'), ('REVEAL', 'Reveal'), ('CLUSTER', 'Cluster'), ('VOTE', 'Vote'), ('DISCUSS', 'Discuss'), ('COMPLETE', 'Complete')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('votes_per_member', models.PositiveIntegerField(default=3)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='cycles.feedbackcycle')),
            ],
        ),
    ]
